### ISSUE TITLE
syntax error in xray_syncTestandPrecond.py script

### ISSUE THREAD

**Issue by tiendungitd** [Xray-App/xray-cloud-mig#4]
When running xray_syncTestandPrecond.py script, I got the syntax error:
```
 Traceback (most recent call last):
File "xray_syncTestandPrecond.py", line 130, in <module>
json_data_pre = json.loads(r.text)
File "/usr/lib/python3.7/json/_init_.py", line 348, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I guess something wrong in xray_variables.py, but could not find it, please see attachment for xray_variables.py, I marked some sensitive information.

[xray_variables.txt](https://github.com/Xray-App/xray-cloud-mig/files/6076519/xray_variables.txt)

Thanks.

**Comment by bmpc** [comment]
Hi @tiendungitd,

I can't find the file attached!

Bruno.

**Comment by tiendungitd** [comment]
Hi @bmpc ,
Sorry, I just added the attachment, please have a look.

**Comment by bmpc** [comment]
It seems this error happens after a request to fetch all Preconditions associated with a Test. You'll have to edit the "xray_syncTestandPrecond.py" file and add a print between line 130 to check what is the result returned from Jira in this request.

`print(r.text)`

**Comment by tiendungitd** [comment]
Hi @bmpc 
Here is result after add print(r.text), but the issue FFAG-26594 is existing in server and cloud, this is a test type.
```
2021-03-04 12:40:14,589 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): j
Issue with key FFAG-26594 not found or is not of type Test.
Traceback (most recent call last):
  File "xray_syncTestandPrecond.py", line 131, in <module>
    json_data_pre = json.loads(r.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by bmpc** [comment]
Hi @tiendungitd,

How many issue types named "Test" do you have in your Jira server instance?

If you have just one (I presume the one from Xray) then please open a ticket in our help desk: https://jira.xpand-it.com/servicedesk/customer/portal/2

This is probably a problem with the Xray REST API that is not recognising some issues as being tests.

Bruno

**Comment by tiendungitd** [comment]
Hi @bmpc 
I have two issue types named "Test"
![image](https://user-images.githubusercontent.com/21011388/110906622-c4544480-833e-11eb-9514-a0774c4667e2.png)

**Comment by bmpc** [comment]
Hi @tiendungitd,

In this case, you need to remove the Zephyr Test issues from the Tests JQL. A simpler way to do it is to rename the zephyr issue type to "Zephyr Test"

**Comment by tiendungitd** [comment]
Hi @bmpc 
After rename the zephyr issue type, I can get rid of this issue, but I got another error:
```
2021-03-16 11:13:05,348 - root - INFO - Ohh dear...
2021-03-16 11:13:05,349 - root - INFO - {"errors":[{"message":"Error adding Preconditions to Test: preconditions with the following ids not found: 100069!","locations":[{"line":1,"column":13}],"path":["zjlcxjwwir"]},{"message":"Error adding Preconditions to Test: preconditions with the following ids not found: 100069!","locations":[{"line":1,"column":171}],"path":["ynhwqbqgnr"]},{"message":"Error adding Preconditions to Test: preconditions with the following ids not found: 100069!","locations":[{"line":1,"column":329}],"path":["ezisjriydv"]}],"data":{"zjlcxjwwir":null,"ynhwqbqgnr":null,"ezisjriydv":null}}
2021-03-16 11:13:05,349 - root - INFO - Ohh dear...
2021-03-16 11:13:05,349 - root - INFO - {"errors":[{"message":"Error adding Preconditions to Test: preconditions with the following ids not found: 100069!","locations":[{"line":1,"column":13}],"path":["zjlcxjwwir"]},{"message":"Error adding Preconditions to Test: preconditions with the following ids not found: 100069!","locations":[{"line":1,"column":171}],"path":["ynhwqbqgnr"]},{"message":"Error adding Preconditions to Test: preconditions with the following ids not found: 100069!","locations":[{"line":1,"column":329}],"path":["ezisjriydv"]}],"data":{"zjlcxjwwir":null,"ynhwqbqgnr":null,"ezisjriydv":null}}
```

**Comment by bmpc** [comment]
Hi @tiendungitd,

Please make sure the "**Pre-Conditon**" issues from Xray server where correctly migrated to "**Preconditon**" issues in Xray cloud.

As per the documentation:
"""
Preconditions have been properly handled for been compatible with Atlassian Cloud.X-ray uses 'Pre-Condition' issue type On-Premise while in Cloud uses 'Precondition'. Issues need to be moved/update accordingly.
"""

You need to change the Pre-Condition issue type do Precondition.

Have you done this already?

Bruno.

**Comment by tiendungitd** [comment]
Hi @bmpc 
I just changed Pre-Condition issue type to Preconditon, reindex in xray cloud and xray server, but the issue still persist

![image](https://user-images.githubusercontent.com/21011388/111596836-2bbb3a00-8800-11eb-92bb-11a77249feba.png)


Do I need to change Pre-Condition custom field to Precondition also?
Thanks

**Comment by tiendungitd** [comment]
Hi @bmpc 
My issue is fixed. In Jira cloud, I have to add Precondition and remove Pre-condition issue type to corresponding issue type schemes.
Thanks for your support
