### ISSUE TITLE
SyncTestExecswithTest

### ISSUE THREAD

**Issue by mkal18** [Xray-App/xray-cloud-mig#7]
Hi,
I get this error when syncing test execs with tests
/xraystaging/xray_syncTestExecWithTests.py", line 426, in <module>
    arrayOfArraysofIds = np.array_split(listoftests, numberOfIterationsRounded)
  File "/Users/x/PycharmProjects/pythonProject1/venv/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 754, in array_split
    raise ValueError('number sections must be larger than 0.')
ValueError: number sections must be larger than 0.

What basically ends up happening is that the test execs link to a test , assignee etc are updated but the status isn't.

**Comment by lfcribeiro** [comment]
Hello,

Could you please provide more logs ? - The "listoftests" is unexpectedly empty and logs provide a visibility of the process being done.

Can you also add above  line 232 - 
logging.info("Adding - Id...." + cloudTest.id)
logging.info("Adding - Key...." + cloudTest.key)

So it provides the information on the test being added to the list that is creating problems.

Kind Regards,

**Comment by mkal18** [comment]
[XRAYTESTlog.txt](https://github.com/Xray-App/xray-cloud-mig/files/6420448/XRAYTESTlog.txt)

Hi please find attached, also note I did change the following before: 

+ GLOBAL_onCloudMig+'/rest/api/3/user/search?query=' + str(executeronPremiseUsername) +'', auth=HTTPBasicAuth(GLOBAL_cloudUser, GLOBAL_apitoken) )
responseForAssignee = requests.get('' + GLOBAL_onCloudMig+'/rest/api/3/user/search?query=' + str(assigneeonPremiseUsername) +'',  auth=HTTPBasicAuth(GLOBAL_cloudUser, GLOBAL_apitoken))

Because otherwise the script wouldnt even link the execs to the tests. I would get this error :2021-04-20 13:37:56,680 - root - INFO - [Getting detail for sync] - Status....
Traceback (most recent call last):
  File "/Users/mamtakalwani/PycharmProjects/pythonProject1/xraystaging/xray_syncTestExecWithTests.py", line 252, in <module>
    responseForUser = requests.get('' + GLOBAL_onCloudMig+'rest/api/3/user/search?query=' + str(executerOnPremisseUser.emailAddress) +'', auth=HTTPBasicAuth(GLOBAL_cloudUser, GLOBAL_apitoken) )
  File "/Users/mamtakalwani/PycharmProjects/pythonProject1/venv/lib/python2.7/site-packages/jira/resources.py", line 177, in __getattr__
    raise AttributeError("%r object has no attribute %r (%s)" % (self.__class__, item, e))
AttributeError: <class 'jira.resources.User'> object has no attribute 'emailAddress' ('User' object has no attribute '__getitem__')

 

Process finished with exit code 1

**Comment by mkal18** [comment]
Now it links, the test execs to the tests, adds the correct assignee too. It just doesn't update the test run status - i.e. the fact that is has been executed,
I have attached the logfile which gives that error.

**Comment by lfcribeiro** [comment]
Hello,

for what I can see its not updating anything in the test runs.
If appears that the a list is comming empty.

Please print in the logs the values of the variables (fullList,numberOfIterations,numberOfIterationsRounded,arrayOfArraysofIds  ) after the following code (near line 422):
fullList = listoftests
numberOfIterations=len(fullList)/100
numberOfIterationsRounded = math.ceil(numberOfIterations)
 arrayOfArraysofIds = np.array_split(listoftests, numberOfIterationsRounded)

**Comment by mkal18** [comment]
([xray_syncTestExecWithTests.py.zip](https://github.com/Xray-App/xray-cloud-mig/files/6437114/xray_syncTestExecWithTests.py.zip))](url)

Helllo,
please see attached my modified script the changes I made are reflected below:

Change 1: Line 108/109  - commented out due to the path not being declared - it wouldnt run at at all,

Due to Original File Error #1 -  line 109, in <module>
    if path.exists(commandExecutionExceptions.export):
  File "/Users/mamtakalwani/PycharmProjects/pythonProject/venv/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found


Change 2: Line 251 & Line 269 - changed to onPremiseUser.username - as it wouldnt recognise the email address associated with the user

Due to Original File Error 2 -  Traceback (most recent call last):
  File "/Users/mamtakalwani/PycharmProjects/pythonProject1/xraystaging/xray_syncTestExecWithTests.py", line 252, in <module>
    responseForUser = requests.get('' + GLOBAL_onCloudMig+'rest/api/3/user/search?query=' + str(executerOnPremisseUser.emailAddress) +'', auth=HTTPBasicAuth(GLOBAL_cloudUser, GLOBAL_apitoken) )
  File "/Users/mamtakalwani/PycharmProjects/pythonProject1/venv/lib/python2.7/site-packages/jira/resources.py", line 177, in __getattr__
    raise AttributeError("%r object has no attribute %r (%s)" % (self.__class__, item, e))
AttributeError: <class 'jira.resources.User'> object has no attribute 'emailAddress' ('User' object has no attribute '__getitem__')


--- Only once  i updated these two lines above does the script run, link the execs to the tests, and update the original value for assignee. in the assignee columm. Just not the  actual test run status.



Error#3 - Due to the changes above, i Believe it added the following error:
Traceback (most recent call last):
  File "/Users/mamtakalwani/PycharmProjects/pythonProject1/xraystaging/xray_syncTestExecWithTests.py", line 426, in <module>
    arrayOfArraysofIds = np.array_split(listoftests, numberOfIterationsRounded)
  File "/Users/mamtakalwani/PycharmProjects/pythonProject1/venv/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 754, in array_split
    raise ValueError('number sections must be larger than 0.')
    
    ---
After multiple logs/printing the errors I noticed that it adds a 'u' when I print the fullList, - hence I have edited the replaces from line 418, 419 and 428. 

^^ this didnt work, I have now raised an issue here.

I have even done a full reindex of my instance & ran everything without modifying your script, but it doesn't work at all unless I make the first two changes on line 108/251 on the original file downloaded from here.

I will now need to come back to you regarding further printing of values over the weekend/Monday as we are reimporting some data. So I will need to run all the scripts again from Cucumber definitions & will come back to you when I have prepped & done those.

**Comment by lfcribeiro** [comment]
Hello,

You are running this with python2.7 for what I can see..
Its required python3.x as stated in the README.md file.

Please make sure you follow all the steps in the README regarding the python requirements as well other steps.

Please run it with python 3.x and let me know the outcome.

Kind regards

**Comment by mkal18** [comment]
Ah, okay. I will do this tomorrow and come back to you!
Thank you!

**Comment by mkal18** [comment]
Hello,
I now get an SSL error which I didnt get beforr when I used python 2.7 SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))] errno:None on GET <client url>

**Comment by lfcribeiro** [comment]
Hello,

Can you give me the location of that error ?
If that was around any call "requests.get" try to add verify=False as a parameter like in generic example below
"r = requests.get(url=URL, params=PARAMS, verify=False)"

kind regards

**Comment by mkal18** [comment]
Its just right in the beginning doesnt recgonise my credentials & says SSL error, when I dindt have that when I ran it with 2.7 python. All the other scripts have worked fine on python 2.7

**Comment by bitcoder** [comment]
> Its just right in the beginning doesnt recgonise my credentials & says SSL error, when I dindt have that when I ran it with 2.7 python. All the other scripts have worked fine on python 2.7

I think this was related to the fact the URL for Xray cloud endpoint changed. The scripts were updated to reflect it.
If no other feedback is provided, we'll close this issue ok?
